options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
rules:
  indentation:
  - 2
  -
    size: 2

  class-name-format: 
  - 2
  -
    convention: hyphenatedlowercase

  brace-style: 
  - 2
  -
    style: 1tbs
    allow-single-line: false

  no-ids: 2
  one-declaration-per-line: 2
  final-newline: 2
  space-after-colon: 2
  empty-line-between-blocks: 2
  trailing-semicolon: 2
  single-line-per-selector: 2
  space-before-colon:
  - 2
  -
    include: false

  space-before-brace: 
  - 2
  -
    include: true

  space-before-bang: 0

  extends-before-mixins: 0
  extends-before-declarations: 0
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations: 0

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 0
  no-debug: 0
  no-disallowed-properties: 0
  no-duplicate-properties: 0
  no-empty-rulesets: 0
  no-extends: 0
  no-important: 0
  no-invalid-hex: 0
  no-mergeable-selectors: 0
  no-misspelled-properties: 0
  no-qualifying-elements: 0
  no-trailing-whitespace: 0
  no-trailing-zero: 0
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-domains: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  no-warn: 0
  property-units: 0

  # Nesting
  declarations-before-nesting: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  function-name-format: 0
  id-name-format: 0
  mixin-name-format: 0
  placeholder-name-format: 0
  variable-name-format: 0

  # Style Guide
  attribute-quotes: 0
  bem-depth: 0
  border-zero: 0
  clean-import-paths: 0
  empty-args: 0
  hex-length: 0
  hex-notation: 0
  leading-zero: 0
  max-line-length: 0
  max-file-line-count: 0
  nesting-depth: 0
  property-sort-order: 0
  pseudo-element: 0
  quotes: 0
  shorthand-values: 0
  url-quotes: 0
  variable-for-property: 0
  zero-unit: 0

  # Inner Spacing
  space-after-comma: 0
  
  
  
  space-after-bang: 0
  space-between-parens: 0
  space-around-operator: 0

  
  
